Step3 - 틱택토(중급)
next-step/android-tictactoe pull request #14
Opened 2023-08-18 12:15 UTC by Gyuil-Hwnag

### 작업 내용
1. Board 클래스로 변경 & Empty 상수화
2. GameResultManager 제거 & map으로 기능 이전
3. Tictactoc 전략 인터페이스화 & DefaultTictactoc에 주입
4. TictactocMap 초기화 부분 수정
5. 틱택토(중급) 기능 구현

2023-08-19 04:57 UTC, malibinYun requested changes
3단계 미션 고생 많으셨습니다 :)
도메인 로직 위주로 피드백을 남겼습니다.
또, 도메인 로직에 단위 테스트가 적어보입니다. 모든 도메인 로직에 대해서 단위 테스트를 꼭 작성해주세요 :)
피드백 반영 후 다시 리뷰 요청 부탁드려요!

2023-08-19 04:57 UTC, malibinYun commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/DefaultTictactoe.kt
> +
틱택토 게임의 전략은 분리되었지만, 그 전략을 실행시키는 것을 대리하는 객체에 지나지 않습니다.
`돌을 놓는 전략` 만이 분리된 게 맞을지 고민해보시면 좋겠어요!

틱택토 게임 공용으로 쓰이는 역할들은 이 Tictactoe 객체에 위치시키고, 돌을 놓는 전략만을 분리해보시면 좋겠어요!
특히, TicTacToe Map 을 전략내에서 생성할 필요는 없어보이네요!
아래 처럼 전략 객체에게 보드판을 전달하면 다음 좌표를 전달 받게 만들어볼 수 있겠네요 :)

```koltin
fun interface Strategy {
    fun getNextPoint(map: Map): Point
}
```
위 코드와 동일하게 구현하라는 의미가 아니이니, 참고 정도로 활용해주세요 :)

2023-08-19 04:57 UTC, malibinYun commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/RandomMiddleTictactoc.kt
> +    }
랜덤 돌을 놓는 전략을 생성자로부터 받게 구현한다면,
중간 난이도에 대한 역할만 구현하고, 랜덤을 놓아야할 때는 주입 받은 랜덤 전략을 통해 돌을 놓게 해보는 건 어떨까요?

중복된 로직을 줄이고, 기존 로직을 활용해볼 수 있게됩니다 :)

2023-08-19 04:57 UTC, malibinYun commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/RandomMiddleTictactoc.kt
> +
tictactoeMap객체 내의 값을 직접 꺼내서 활용하기보다,
tictactoeMap객체에게 메시지를 던져서, 2목이고, 남은 한 자리가 있는 Row의 목록을 가져오게 만들어보는 건 어떨까요?
map에서 3개의 열, 3개의 행, 2개의 대각선을 모두 순회하면서,
그 중 AI가 승리할 수 있는, 혹은, 플레이어를 방해할 수 있는 Row의 목록을 받아온 뒤,
입맛에 맞게 남은 돌의 좌표를 구해 그 좌표를 반환해주면 좀 더 객체 간의 협업을 할 수 있게 만들어볼 수 있겠어요 🙂

2023-08-19 04:57 UTC, malibinYun commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/model/TictactocMap.kt
> +        return getGameResult(point = point, map = map, currentTurn = currentTurn)
getGameResult 함수를 직접 호출하지 않는 이유가 있을까요?
getGameResult 함수는 TictactoeMap에 옮기면서 알맞게 수정이 가능해 보이네요 :)

2023-08-19 04:57 UTC, malibinYun commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/model/TictactocMap.kt
>      fun getMapRowColumn(row: Int, column: Int): Turn {
이 메서드는 get operator를 오버로딩 해볼 수 있겠네요 :)

2023-08-21 15:26 UTC, Gyuil-Hwnag commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/DefaultTictactoe.kt
> +
아하!! 그러네요!! 돌을 놓는 put 전략만 따로 뺴서 관리하도록 수정해볼게요~ 피드백 감사합니다 👍

2023-08-21 15:27 UTC, Gyuil-Hwnag commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/RandomMiddleTictactoc.kt
> +    }
그러네요!! 랜덤 전략에 난이도를 받도록 수정하도록 하겠습니다~ 감사합니다!!

2023-08-21 15:28 UTC, Gyuil-Hwnag commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/RandomMiddleTictactoc.kt
> +
그렇게도 가능하겠네요!! 해당 내용 살펴보면서 수정하도록 하겠습니다~

2023-08-21 15:29 UTC, Gyuil-Hwnag commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/model/TictactocMap.kt
> +        return getGameResult(point = point, map = map, currentTurn = currentTurn)
getGameResultFromSetMapPoint() 함수 자체의 기능을 나누기 위해서 이렇게 작업을 했는데 해당 내용 살펴보면서 수정하도록 하겠습니다~ 감사합니다 👍

2023-08-21 15:29 UTC, Gyuil-Hwnag commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/model/TictactocMap.kt
>      fun getMapRowColumn(row: Int, column: Int): Turn {
그러네요!! 위의 피드백 진행하면서 하나의 함수의 기능으로 묶도록 수정 해보도록 하겠습니다~

2023-08-21 15:31 UTC, Gyuil-Hwnag commented
@malibinYun 
리뷰어님~ 이번주에 휴가가 겹쳐서 이제서야 확인을 했네요ㅠㅠ
해당 피드백 내용 목요일에 복귀해서 피드백 반영후에 리뷰 요청 다시올리도록 하겠습니다!!
감사합니다 👍

2023-08-24 09:46 UTC, Gyuil-Hwnag commented
@malibinYun 
리뷰어님 피드백 반영 하였습니다~

### 작업 내용
1. 전략에서는 돌을 놓는 put만 가지도록 수정 [354d633]
2. TictactocMap 에서 getGameResultFromSetMapPoint를 통해서 gameResult 호출하던 내용 수정 [d643c68]
3. TictactocMap 에서 다음에 랜덤으로 둘 곳 판별하는 로직 가지도록 수정 [ae8785f]
4. RandomStrategy 에서 사용하는 함수들 통합 [22cfa4d] [1e43e31]
5. 랜덤 전략 테스트 코드 추가 [1f070d7] [ecb3e59]

2023-08-25 08:28 UTC, malibinYun approved these changes
쉽지 않은 내용이셨을 텐데, 피드백 반영 고생 많으셨어요!
생각해보면 좋을 점들에 코멘트 남겨두었습니다.
피드백은 다음 미션에 반영해주세요!

2023-08-25 08:28 UTC, malibinYun commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/DefaultTictactoe.kt
> +    fun getMap() = tictactocMap.getMap()
저는 멤버 변수와 메서드의 리턴 타입을 모두 명시해주는데요,
해당 타입을 직관적으로 알기 위함이에요.

제가 겪은 예시로는, int list의 최댓값을 구하는 메서드를 만든 적이 있어요.

```
fun foo() = bar.max()
```

이전 코틀린 버전에서는 max()의 리턴 타입이 Int? 였는데요, 실제로 foo() 메서드를 사용하면, 자꾸 빨간 줄이 뜨고 알고 보니 nullable하기 때문에 나타나던 현상이었어요.
이렇게 구분하기 어려웠던 문제들이 저만 겪은 문제가 아니었는지, 현재 코틀린 버전에서는 maxOrNull()로 이름이 변경되었더라구요.

또, Effective Kotlin Item 4에 `Inferred Type으로 리턴하지 말라` 라는 챕터가 있어요.
타입 추론으로 구현체가 리턴이 되지, 상위 타입의 인터페이스 등이 세팅이 되지 않기 때문에 원하는 의도를 해칠 수 있다는 내용이에요.
Item 14 `변수 타입이 명확하지 않은 경우 확실하게 지정하라` 라는 챕터에도 짧게 관련 내용을 확인해보실 수 있어요! 🙂

2023-08-25 08:28 UTC, malibinYun commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/RandomMiddleTictactoc.kt
> +    override fun put(point: Point, tictactocMap: TictactocMap): GameResult {
RandomStrategy를 따로 구현하셨네요!

제가 이전에 남겨드린 피드백은, 랜덤 TictactocStrategy 구현을 RandomMiddleTictactoc에서 갖고 있게 시도해보시라는 의미었습니다. 그래서 러프하게 아래 처럼, 랜덤 전략을 그대로 사용해보는 형태를 의도했습니다 :)

```kotlin
class MiddleMode(
    class randomGameMode: GameMode = RandomMode()
): GameMode {

    fun put(...) {
        if (방해할 수 있는 경우 || 승리 직전인 경우) {
            put() // middle에서 사용할 알고리즘을 담은 put
        } else {
            randomGameMode.put() 
        }
    }
}
```

2023-08-25 08:28 UTC, malibinYun commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/model/TictactocMap.kt
> +    }
한 메서드가 하나의 일만 하도록 만들어보는 건 어떨까요?
메서드의 길이를 좀 더 줄여내볼 수 있을거라 기대됩니다 :)

2023-08-25 08:28 UTC, malibinYun commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/model/TictactocMap.kt
> +    }
이 메서드들은 비슷한 형태로 조금씩 값이 달라지는데요,
좀 더 추상화하면 하나의 메서드를 재활용해볼 수도 있어 보입니다 :)

각 열 및 대각선에 대한 내용을 가지는 객체를 만들어보는 건 어떨까요?
정보만을 가지는 것으로도 한 단계 추상화해볼 수 있어보입니다

2023-08-25 08:28 UTC, merged

2023-08-26 07:30 UTC, Gyuil-Hwnag commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/DefaultTictactoe.kt
> +    fun getMap() = tictactocMap.getMap()
아하 그렇군요!! 해당 내용 참고하도록 하겠습니다~ 정말 감사합니다ㅎㅎ

2023-08-26 07:31 UTC, Gyuil-Hwnag commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/RandomMiddleTictactoc.kt
> +    override fun put(point: Point, tictactocMap: TictactocMap): GameResult {
아하 그렇군요ㅠㅠ 제가 의도를 잘못파악 했었네요..
해당 내용도 참고하도록 하겠습니다!!

2023-08-26 07:31 UTC, Gyuil-Hwnag commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/model/TictactocMap.kt
> +    }
그러게요!! 이부분은 함수가 너무 많은 일을 하고 있네요..

2023-08-26 07:32 UTC, Gyuil-Hwnag commented on domain/src/main/java/com/nextstep/edu/tictactoe/domain/model/TictactocMap.kt
> +    }
오호!! 그러네요!! map에서 정보를 가질 수 있도록 내용 수정해보겠습니다~ 감사합니다ㅎㅎ