feat: 1단계 - 틱택토(2인)
next-step/android-tictactoe pull request #2
Opened 2023-02-25 16:38 UTC by hj1115hj

feat: 1단계 - 틱택토(2인)

2023-02-26 14:56 UTC, malibinYun requested changes
1단계 미션 고생 많으셨습니다 :)
전반적으로 객체 지향 생활 체조를 지켜보면서 코드를 작성해보시길 추천드려요! 😀
고민해볼만한 곳에 코멘트 남겨두었습니다.
피드백 반영하시고 다시 리뷰 요청부탁드릴게요!

2023-02-26 14:56 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivity.kt
> +
사실 이기고 진 것은 에러가 아닌데 에러로 취급하고 있네요.
구체적인 이름으로 바꿔보는 것은 어떨까요? 

혹은, Sealed class/interface를 활용해서 메시지를 나타내볼 수도 있겠네요 :)

2023-02-26 14:56 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivityBindingAdapter.kt
> +    if (point == true) {
Boolean를 인자로 받는데, "android:src" 같이 범용적인 이름을 사용하면, 다른 개발자들이 기능을 오해할 것이 우려돼요.
저 구체적인 이름을 써보는 것은 어떨까요?

2023-02-26 14:56 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainViewModel.kt
> +    val point: Array<Array<LiveData<Boolean?>>>
템플릿이 많이 겹쳐있어 가독성이 떨어집니다.
먼저, Array() 하나에 의미를 부여한 객체를 만들어보는 것은 어떨까요?
그리고, 게임판 하나를 의미하는 객체를 만들어보시면 좋겠어요 :)

2023-02-26 14:56 UTC, malibinYun commented on app/src/main/res/layout/activity_main.xml
> +            type="camp.nextstep.edu.tictactoe.domain.Point" />
이 객체를 반드시 가져야할까요?
누를때 바로 Point 객체를 넘겨보는 것은 어떨까요?

2023-02-26 14:56 UTC, malibinYun commented on app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{() -> vm.isWin(point.getPoint(0,0)) }"
누를 때마다 "이겼니?" 하고 묻는 게 매우 어색해보여요.
또 is~ 접두사는 Boolean을 반환하는 내용의 자바 컨벤션입니다.
더 적절한 이름을 찾아보아요 😊

2023-02-26 14:56 UTC, malibinYun commented on app/src/main/res/layout/activity_main.xml
> +            android:src="@{vm.point[0][0]}" />
vm.point[][] 가 무엇을 반환하는지, src는 무슨 의미인지(BindingAdatper로 구현되어있는지) 다른 개발자가 봤을 때 한 번에 알아볼 수 있을까요?

2023-02-26 14:56 UTC, malibinYun commented on app/src/test/java/camp/nextstep/edu/tictactoe/MainViewModelTest.kt
> +        viewModel.isWin(Point(2, 2)) //x
```kotlin
/*
 * X O X
 * O X O
 * X O X
*/
```
이런 식으로 주석으로 남겨보는 것은 어떨까요?
그런데 위 케이스는 무승부가 아닌 것 같은데.. 무언가 다른 룰이 있는걸까요?! 😱

2023-02-26 14:56 UTC, malibinYun commented on domain/src/main/java/camp/nextstep/edu/tictactoe/domain/Ticktacktoe.kt
> +package camp.nextstep.edu.tictactoe.domain
도메인이 모듈에 파일이 하나 뿐이네요!
각 객체들을 잘 나누어서 파일로 분리해주세요 :)

2023-02-26 14:56 UTC, malibinYun commented on domain/src/main/java/camp/nextstep/edu/tictactoe/domain/Ticktacktoe.kt
> +
r, c 같은 축약어의 사용을 지양해주세요.

Point 객체가 다른 포인트를 생성만 하는 로직을 가지고 있는 것은 어색해 보여요.
Point는 9개 밖에 없으니, 9개를 캐싱해서 사용하는 방법도 있겠네요 :)

2023-02-26 14:56 UTC, malibinYun commented on domain/src/main/java/camp/nextstep/edu/tictactoe/domain/Ticktacktoe.kt
> +    }
한 메서드가 너무 많은 일을 하고 있어, 가독성이 떨어집니다 :)
먼저 단일 책임 원칙으로 메서드를 분리해보는 것은 어떨까요?
그리고 객체지향 생활 체조를 지켜서 로직을 구성해보세요! 😀

2023-02-26 14:56 UTC, malibinYun commented on domain/src/test/java/camp/nextstep/edu/domain/MyClassTest.kt
> +        assertEquals(Turn.X, currentTurn)
Truth를 활용해서 검증문을 구성해주세요 :)

2023-02-27 04:54 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivity.kt
> +
when 에서 else 사용 없이  하위 타입의 모든 class 분기 하기 위해서 sealed class내의 하위 클래스를 선언해서 사용하는 것으로 알고 있는데요 이건 enum에서도 동일하게 정의된 모든 enum 값들일 when에서 분기 할 수 있는 것으로 알고 있습니다. 
sealed 사용
```
   private fun showTurnResultMessage(message: TurnResultMessage) {
        when (message) {
            is ErrorMessage -> Toast.makeText(this, "게임이 종료되었습니다.", Toast.LENGTH_SHORT).show()
            is FinishMessage -> Toast.makeText(this, "X가 이겼습니다", Toast.LENGTH_SHORT).show()
            is OWinMessage -> Toast.makeText(this, "O가 이겼습니다", Toast.LENGTH_SHORT).show()
            is TieMessage -> Toast.makeText(this, "무승부 입니다", Toast.LENGTH_SHORT).show()
            is XWinMessage -> Toast.makeText(this, "다른 곳을 선택해 주세요", Toast.LENGTH_SHORT).show()
        }
    }
```
enum사용
```
    private fun showTurnResultMessage(message: MessageState) {
        when (message) {
            X_WIN -> TODO()
            O_WIN -> TODO()
            ERROR -> TODO()
            FINISH -> TODO()
            IN_A_TIE -> TODO()
        }
    }
```

다른 의도로 sealed나 interface 사용을 권장하신 건지 그렇다면 어떤 것인지 궁금합니다! :)

2023-02-27 05:15 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivityBindingAdapter.kt
> +    if (point == true) {
구체적인 이름 제시 해주실 수 있으실까요? 
어떤걸 오해한다는 건지 모르겠어요 ㅜㅜ .


저는 android:src로 기존과 같게해서 이미지를 변경하는 bind adapter인 걸 즉각적으로 알 수 있도록 한 의도였는데 

```kotlin 
@BindingAdapter("bind:drawXorOWithPoint")
```
이거 말고는 생각이 안드네용
다른건 잘 안떠오르네용..

2023-02-27 06:02 UTC, hj1115hj commented on app/src/main/res/layout/activity_main.xml
> +            type="camp.nextstep.edu.tictactoe.domain.Point" />
xml 내에서  데이터를 전달하기 위해서는 variable에 선언되어야 하는거 아닌가용? 바인딩 없이 누를 때 Point 객체를 넘기 수 있나요?

2023-02-27 13:38 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivity.kt
> +
네 말씀해주신대로 enum도 같은 특징을 지니고 있지요.
sealed를 언급했던건, 에러인지, 메시지인지, 또, 메시지를 세부적으로 분류할 수도 있으니 활용해보면 좋겠다는 의미였어요 :)
어떤 것을 선택할 지는 리뷰이님 몫입니다.

2023-02-27 13:42 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivityBindingAdapter.kt
> +    if (point == true) {
정해진 정답은 없기에 리뷰이님이 충분히 고민하셔서 작명을 해보셨으면 좋겠어요! 🙂
스스로 공부하면서 결과를 내보는 것이 주 목표인 교육이기에, 천천히 충분히 고민하는 시간을 가지시면 좋겠습니다 :)

첨언하면, android:src는 기존과 같으면, xml에 세팅되는 값은 image 리소스라고 오해할 수 있습니다.
이 코드를 처음 보는 사람은 image View의 android:src에 boolean이 들어가는 BindingAdapter가 작성되어있는 지 알 수 없기 때문이에요. 새로운 무언가이기에 BindingAdapter를 찾아봐야겠다는 단서 조차 얻기 어려워지겠지요 :)

2023-02-27 14:00 UTC, malibinYun commented on app/src/main/res/layout/activity_main.xml
> +            type="camp.nextstep.edu.tictactoe.domain.Point" />
Point 객체를 생성하면서 넘길 수는 없지만, Enum등으로 미리 만들어본다면 넘길 수 있기에 해당 내용을 의도했어요 :)
혹은, 좌표만을 넘길수도 있겠지요.
방법은 너무 다양하지만, variable을 제거하는 방법을 고민해보셨으면 좋겠어요 :)

2023-02-27 14:18 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivityBindingAdapter.kt
> +    if (point == true) {
감사합니다~ 이해했어요! ㅎㅎ바인드 어뎁터라는 단서가 어렵울수 있겠내요!

2023-02-27 15:15 UTC, hj1115hj commented on domain/src/main/java/camp/nextstep/edu/tictactoe/domain/Ticktacktoe.kt
> +
네엡~ 캐싱하는 방법도 좋은 방법 인 것 같아요 저는 data class로 만들어서 코틀린 코드내에서 Point를 따로 생성하는 경우에 사용 할려고 했었는데 
상수로 하면 데이터 생성을 못해서요.
그런데 미리 상수로 선언해 놓으면 여러가지 잘못된 객체 생성에 의해 발생 하는 오류를 사전에 잡을 수 있으니 좋은 것같아요

2023-02-27 15:17 UTC, hj1115hj commented on domain/src/main/java/camp/nextstep/edu/tictactoe/domain/Ticktacktoe.kt
> +
그런데 생성하는 로직만 갖고 있는게 어떤 점에서 어색한건 가요?  point의 row, column을 바꿔서 다양한 형태의 Point를 만드는 data class generater라고 생각 할 수 있을것 같은데요 
data class가 지켜야하는 느낌이나? 규칙이 있나요?

2023-02-27 15:46 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainViewModel.kt
> +    val point: Array<Array<LiveData<Boolean?>>>
``` kotlin
  private val point = MutableLiveData<Boolean?>(null)
   private val columns = Array(MAP_SIZE) { point }
   private val _map = Array(MAP_SIZE) { columns }
```

이렇게 추상화 해보았는데 

한번 클릭하면 전체 선택이 되네용

혹시 원인 안실까요.

```kotlin
   private val columns = Array(MAP_SIZE) { MutableLiveData<Boolean?>(null)}
    private val _map = Array(MAP_SIZE) { columns }
 
```
요렇게 하면 columns만 전체 선택되용..;
바인딩은 아래와 같이 하고 있습니다.

```xml
  bind:drawOorXWithPoint="@{vm.map[1][0]}" 
```

2023-02-27 15:52 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivity.kt
> +
:) sealed로 분류하고, 다양한 메시지를 포함 할 수 있군요!ㅜ 조금 더 공부해 봐야겠습니다

2023-02-27 16:05 UTC, hj1115hj commented on domain/src/main/java/camp/nextstep/edu/tictactoe/domain/Ticktacktoe.kt
> +    }
~>_< 객체지향 생활체조 알려주셔서 감사해요~

2023-02-27 17:31 UTC, hj1115hj commented on domain/src/main/java/camp/nextstep/edu/tictactoe/domain/Ticktacktoe.kt
> +package camp.nextstep.edu.tictactoe.domain
넵넵~

2023-02-27 17:31 UTC, hj1115hj commented on app/src/test/java/camp/nextstep/edu/tictactoe/MainViewModelTest.kt
> +        viewModel.isWin(Point(2, 2)) //x
👍 👍 👍

2023-02-27 17:33 UTC, hj1115hj commented on app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{() -> vm.isWin(point.getPoint(0,0)) }"
put으로 바꾸어 보았습니다~

2023-02-27 17:53 UTC, hj1115hj commented on app/src/test/java/camp/nextstep/edu/tictactoe/MainViewModelTest.kt
> +        viewModel.isWin(Point(2, 2)) //x
```kotlin 
  /**
     *  X O X
     *  X O O
     *  O X X
     * */
```
입니다~

2023-02-27 18:10 UTC, hj1115hj commented on domain/src/test/java/camp/nextstep/edu/domain/MyClassTest.kt
> +        assertEquals(Turn.X, currentTurn)
```kotlin 
assertThat(currentTurn).isEqualTo(Turn.X)
 assertEquals(Turn.X, currentTurn)
``` 
같은 검증 인거 같은데욤! truth를 사용해서 검증할 다른 케이스도 있는 건가요?

2023-02-27 18:16 UTC, hj1115hj commented on app/src/main/res/layout/activity_main.xml
> +            type="camp.nextstep.edu.tictactoe.domain.Point" />
저는 data class로 만들어서 코틀린 코드내에서 Point를 따로 생성하는 경우에 사용 할려고 했었습니당!
상수로 하면 데이터 생성을 못해서요. 
문득 궁금해서 실무에서 , 보통 variable에는 상수만 선언한용? view model 제외하고는.. 만약 그렇다면 이유가 있나영?

2023-03-01 03:56 UTC, malibinYun requested changes
피드백 반영 고생 많으셨습니다 :)
커밋이 거의 통째로 되어있는데요,
미리 만들어야할 기능 목록 명세를 만들어보고, 그 순서대로 기능 마다 커밋을 나누어서 작성해보는 연습을 하시길 추천드려요 🙂 
다음 미션을 위해 머지하겠습니다~
피드백은 다음 미션에 반영해주세요!

2023-03-01 03:56 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivity.kt
> +                .show()
sealed class를 활용해주셨네요 👍

2023-03-01 03:56 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivityBindingAdapter.kt
> +fun setImageResource(view: ImageView, point: Boolean?) {
Boolean 값 보단, O 혹은 X를 나타내는 객체를 만들어서 활용해보는 것은 어떨까요?

2023-03-01 03:56 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainViewModel.kt
> +    val map: Array<Array<LiveData<Boolean?>>>
여전히 템플릿이 많이 겹쳐있습니다.
`Array() 하나에 의미를 부여한 객체를 만들어보는 것` 은, 래핑해서 새로운 클래스를 만들어보시라는 의미였습니다 :)

2023-03-01 03:56 UTC, malibinYun commented on app/src/main/res/layout/activity_main.xml
> +            android:onClick="@{() -> vm.put(point.CellTopLeft) }"
Enum으로 구현되어있으니, variable로 선언하지 않고, import 해서 직접 넣어줄 수 있겠지요 :)
```
vm.put(Point.CellTopLeft)
```

2023-03-01 03:56 UTC, malibinYun commented on app/src/test/java/camp/nextstep/edu/tictactoe/MainViewModelTest.kt
> +        )
모든 검증문은 Truth로 구현해주세요 :)

2023-03-01 03:56 UTC, malibinYun commented on domain/src/test/java/camp/nextstep/edu/tictactoe/domain/TicktacktoeTest.kt
> +        assertEquals(GameResult.X_WIN, thirdResult.first)
여러 개의 검증문을 나열한 것과, assertAll로 감싼 것은 어떤 차이점이 있을까요?

2023-03-01 03:57 UTC, malibinYun commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainViewModel.kt
> +    val point: Array<Array<LiveData<Boolean?>>>
https://github.com/next-step/android-tictactoe/pull/2#discussion_r1121104560
이 리뷰를 참고해서 먼저 클래스 분리를 시도해보세요 :)

2023-03-01 03:59 UTC, malibinYun commented on app/src/main/res/layout/activity_main.xml
> +            type="camp.nextstep.edu.tictactoe.domain.Point" />
상수만 선언하라는 의미가 아닙니다.
Point의 특성 상 9개의 좌표를 필요할 때마다 만들면 비효율적이기 때문에 제안 드렸습니다 :)
enum이 아니더라도, data class로 만드셔서, 똑같이 한 번만 만들어 활용할 수 있습니다.

2023-03-01 04:04 UTC, malibinYun commented on domain/src/main/java/camp/nextstep/edu/tictactoe/domain/Ticktacktoe.kt
> +
Point는 좌표를 갖고있는 객체인데,
그런 객체에게 getPoint를 하는 것은 어떤 역할을 하는 지 예측하기 어려워보여요 :)
새로운 좌표를 생성해낸다기보다, 스스로의 값을 다시 point로써 반환한다는 의미로 받아들여지네요 :)

point가 getLeftPoint, getRightPoint 메서드를 갖고있다면, 자신의 왼, 오른쪽의 좌표를 가져올 것으로 예상이 됩니다.

getpoint는 생성자나 다름 없어보이는데요, 그렇다면 생성자를 사용하거나 혹은, 팩터리 메서드에 책임을 부여하면 좋겠네요 🙂
의미를 담은 객체가 역할에 맞는 책임을 지니게 만들려고 노력해보시면 좋겠어요 :)

2023-03-01 04:04 UTC, malibinYun commented on domain/src/main/java/camp/nextstep/edu/tictactoe/domain/Ticktacktoe.kt
> +    }
객체지향 생활체조도 지켜보시고, 한 메서드가 하나의 일만 하게도 작성해보세요 :)

2023-03-01 04:05 UTC, malibinYun commented on domain/src/test/java/camp/nextstep/edu/domain/MyClassTest.kt
> +        assertEquals(Turn.X, currentTurn)
수업 시간에 배우신 내용을 잘 상기해보시면 기억 나실 겁니다 :)
Truth를 활용하는 이유는 검증문의 가독성 때문이었지요!
영어 문장 처럼 읽을 수 있게 작성할 수 있는 장점이 있습니다

2023-03-01 04:05 UTC, merged

2023-03-01 12:06 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainActivityBindingAdapter.kt
> +fun setImageResource(view: ImageView, point: Boolean?) {
객체 지향적으로 생각하는건 어렵네요ㅜ 수정하였습니다~ 감사합니당~

2023-03-01 12:17 UTC, hj1115hj commented on domain/src/test/java/camp/nextstep/edu/tictactoe/domain/TicktacktoeTest.kt
> +        assertEquals(GameResult.X_WIN, thirdResult.first)
테스트를 동시 검증 할 수 있네용~ 

https://sas-study.tistory.com/316

2023-03-01 12:57 UTC, hj1115hj commented on domain/src/test/java/camp/nextstep/edu/tictactoe/domain/TicktacktoeTest.kt
> +        assertEquals(GameResult.X_WIN, thirdResult.first)
```kotlin 
   assertAll("Check all conditions",
            { assertEquals(GameResult.UNKNOWN, firstResult.first, "GameResult should be UNKNOWN") },
            {
                assertEquals(
                    GameResult.UNKNOWN,
                    secondResult.first,
                    "GameResult should be UNKNOWN"
                )
            },
            { assertEquals(GameResult.O_WIN, thirdResult.first, "GameResult should be O_WIN") }
        )
``` 
이런식으로 사용할 수 있는것 같아요 
JUnit5 여서 사용해 보려고했으나.. ㅜ 디팬던시 import가 실패했는짖 Test event were not recived 에러가 발생하네요ㅜ 
유익한 정보 감사합니다~

2023-03-01 13:11 UTC, malibinYun commented on domain/src/test/java/camp/nextstep/edu/tictactoe/domain/TicktacktoeTest.kt
> +        assertEquals(GameResult.X_WIN, thirdResult.first)
아! assertAll은 Junit5 기능이 맞습니다.
제가 다른 수업과 착각해서 Junit4에 없는 기능을 소개해드렸네요 ㅠ_ㅠ 죄송합니다

2023-03-02 15:01 UTC, hj1115hj commented on app/src/main/java/camp/nextstep/edu/tictactoe/MainViewModel.kt
> +    val map: Array<Array<LiveData<Boolean?>>>
넴~ 강의 듣고나서 이해하게되었습니다><ㅎㅎ