step2: 틱택토(랜덤)
next-step/android-tictactoe pull request #21
Opened 2023-08-30 06:09 UTC by minhyukseul

랜덤모드 구현을 해보았습니다.

UDF에 기반하여 코드를 작성하려고 하였는데 제가 잘못이해하고 적용한 부분이 있거나 하면 말씀 부탁드리겠습니다.

1단계에서도 너무 꼼꼼한 리뷰 주셔서 많은 부분 생각해볼 수 있었던 것 같습니다.

네이밍 컨벤션 같은 경우 익숙하지 않아 놓치는 부분이 많을 것 같은데요. 

이 부분도 많은 말씀 부탁드리겠습니다.

2023-08-31 05:19 UTC, namjackson requested changes
안녕하세요 성현님!
2단계 고생하셨습니다! 잘구현해주셨네요 👍 
몇가지 고민하실만한 포인트들 코멘트로 남겼으니, 확인해주세요 😄

2023-08-31 05:19 UTC, namjackson commented on tictactoe-app/src/main/java/camp/nextstep/edu/tictactoe/MainActivity.kt
> +                }, 1000L)
tictactoeGame내의 ai가 mark하는 동작이 실행되는 건 도메인의 역할은 아닐까요?
Ui에 의존적인 비즈니스 로직으로도 볼수 있을거 같아요!

도메인내에서 객체들이 협력하는 구조를 고민해보면 어떨까요?

2023-08-31 05:19 UTC, namjackson commented on tictactoe-app/src/test/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModelTest.kt
> +        }
에러를 throw 하기보단, assert문을 활용해도 좋을거 같아요!

2023-08-31 05:19 UTC, namjackson commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/TictactoeGame.kt
> +    private val tictactoeStrategy: TictactoeStrategy = DefaultStrategy()
전략패턴 👍

2023-08-31 05:19 UTC, namjackson commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/strategy/DefaultStrategy.kt
> +class DefaultStrategy : TictactoeStrategy
DefaultStrategy는 무엇을 의미할까요?
2인 모드또한 Strategy로 표현해보면 어떨까요?

2023-08-31 05:19 UTC, namjackson commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/strategy/TictactoeStrategy.kt
> +interface TictactoeStrategy
전략패턴이라는 네이밍에 맞게,
추상화된 동작을하는 함수를 추가해보면 어떨까요?

2023-08-31 05:19 UTC, namjackson commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/TictactoeGame.kt
> +    }
Strategy이라고 하기에는, 동적으로 새로운 Strategy를 추가하기는 힘든 구조인거 같아요! 😄 
비슷한 코멘트 남기긴했는데,
추상화된 동작을 함수로 분리해보면 어떨까요?
TictactoeGame 내부에서 현재의Strategy가 어떤 동작을 하는지에 대한부분은 분리하는부분을 고민해봐도 좋을거 같아요 😄

2023-08-31 05:19 UTC, namjackson commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/TictactoeGame.kt
> +    private val tictactoeStrategy: TictactoeStrategy = DefaultStrategy()
추가된 동작에 대한부분도 테스트코드로 작성해보아요!

2023-08-31 05:26 UTC, minhyukseul commented on tictactoe-app/src/main/java/camp/nextstep/edu/tictactoe/MainActivity.kt
> +                }, 1000L)
말씀하신 부분대로 한번 고민을 해보겠습니다. 화면단을 일단 업데이트를 하고 나서 프로그램이 후 처리를 하는식으로 고민을 하다가 이렇게 구현을 하였는데요. ai가 mark하는 동작 또한 하게 하려면 어떻게 해야 할지 한번 고민해 보도록 하겠습니다.

2023-08-31 05:36 UTC, minhyukseul commented on tictactoe-app/src/test/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModelTest.kt
> +        }
변경 작업을 해봤는데요. 다음 리뷰에 검토 부탁드리겠습니다.

2023-08-31 05:36 UTC, minhyukseul commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/TictactoeGame.kt
> +    private val tictactoeStrategy: TictactoeStrategy = DefaultStrategy()
네 이 부분을 놓쳤네요. 남재님 리뷰 덕분에 아차 싶은 상황이 한 두번이 아니네요. 덕분에 많이 배웁니다.

2023-08-31 05:37 UTC, minhyukseul commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/strategy/DefaultStrategy.kt
> +class DefaultStrategy : TictactoeStrategy
네 일단 기본모드라고 생각을 하고 작성해 보았는데요. 기능에 맞는 이름으로 수정해보겠습니다.

2023-08-31 05:39 UTC, minhyukseul commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/strategy/TictactoeStrategy.kt
> +interface TictactoeStrategy
네 이부분 사실 좀 고민을 했었는데요. 수정해보겠습니다.

2023-08-31 05:41 UTC, minhyukseul commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/TictactoeGame.kt
> +    }
네 이 부분 고민해보고 작업해보도록 하겠습니다.

2023-08-31 13:37 UTC, namjackson requested changes
안녕하세요 성현님!
피드백 반영 잘해주셨네요! 
고민할법한 코멘트 남겼으니 확인해주세요!

2023-08-31 13:37 UTC, namjackson commented on tictactoe-app/src/main/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModel.kt
> +            updateUiStatus(result)
현재 구조상, continueGame이 연쇄적으로 실행이 버그가 있네요!

2023-08-31 13:37 UTC, namjackson commented on tictactoe-app/src/main/java/camp/nextstep/edu/tictactoe/MainActivity.kt
>              }
AI와 유저의 수가 한번에 추가되는 부분과 별도로, 
UI 로직보다는 비즈니스 로직에 가까우니, ViewModel내에서 처리되는게 더 안전하진 않을까요?
UI에 비즈니스 관련 로직이 있다면, 테스트하기도 힘들거같아요!

2023-08-31 13:37 UTC, namjackson commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/strategy/TictactoeStrategy.kt
> +    fun getPosition(tictactoeMap: TictactoeMap): CellPosition?
getPosition보다는 좀더 직관적인 getNextPosition같은 네이밍도 어울릴거 같아요 😄

2023-08-31 13:37 UTC, namjackson commented on tictactoe-domain/src/test/java/camp/nextstep/edu/tictactoe/domain/TictactoeGameTest.kt
> +    fun `Random모드에서 게임을 계속하는 경우 진행상태가 진행중으로 온다`() {
Random 관련 테스트는 어떻게 하면 좋을까요?
테스트용 FakeStrategy객체를 활용해봐도 좋을거 같아요!

2023-08-31 13:37 UTC, namjackson commented on tictactoe-app/src/test/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModelTest.kt
>      }
ViewModel에 추가된 비즈니스 로직또한 테스트코드를 작성해보면 어떨까요?

2023-08-31 23:27 UTC, minhyukseul commented on tictactoe-app/src/main/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModel.kt
> +            updateUiStatus(result)
엇? 확인해보겠습니다.

2023-08-31 23:28 UTC, minhyukseul commented on tictactoe-app/src/main/java/camp/nextstep/edu/tictactoe/MainActivity.kt
>              }
해당 로직을 UI로직에서 걷어내보겠습니다.

2023-08-31 23:29 UTC, minhyukseul commented on tictactoe-domain/src/main/java/camp/nextstep/edu/tictactoe/domain/strategy/TictactoeStrategy.kt
> +    fun getPosition(tictactoeMap: TictactoeMap): CellPosition?
변경해보았습니다.

2023-08-31 23:37 UTC, minhyukseul commented on tictactoe-app/src/main/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModel.kt
> +            updateUiStatus(result)
일단 지금 구조적으로 변경을 해보았는데요. 말씀하신 부분이 또 나오고 있다면 꼭 말씀 부탁드리겠습니다

2023-09-01 00:52 UTC, minhyukseul commented on tictactoe-domain/src/test/java/camp/nextstep/edu/tictactoe/domain/TictactoeGameTest.kt
> +    fun `Random모드에서 게임을 계속하는 경우 진행상태가 진행중으로 온다`() {
FakeStrategy가 테스트더블의 fake를 말씀하시는거 같은데요. 일단 작성은 해봤는데 테스트 더블에 대한 이해도가 낮아 잘 작성하지 못한것 같습니다. 확인 부탁드리겠습니다.

2023-09-01 01:04 UTC, minhyukseul commented on tictactoe-app/src/test/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModelTest.kt
>      }
추가작서해 보았습니다.

2023-09-01 20:50 UTC, namjackson approved these changes
안녕하세요 성현님! 
피드백 적용잘해주셨네요! 👍  고생하셨습니다!
몇가지 추가로 고민할법한 포인트들 코멘트로 남겼으니, 확인해주세요! 
변경사항은 다음단계 진행해주시면서 포함해주셔도 좋을거같아요!

2023-09-01 20:50 UTC, namjackson commented on tictactoe-domain/src/test/java/camp/nextstep/edu/tictactoe/domain/strategy/FakeStrategy.kt
> +}
FakeStrategy도 Random 기능이라 테스트하기가 힘든 구조네요! 
FakeStrategy의 getNextTurnPosition의 리턴값을 컨트롤할수있다면, 
좀더 구체적인 테스트가 가능해질거같아요 😄 
```
        // given
        val fakeStrategy = FakeStrategy(listOf(CellPosition.TOP_LEFT, ...))
        game = TictactoeGame(fakeStrategy)

```
실제로 Strategy의 역할과 원하는 리턴값을 관리하여, 구체적인 테스트를 작성해보아요!

2023-09-01 20:50 UTC, namjackson commented on tictactoe-app/src/test/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModelTest.kt
> +        }
else 문을 타는 경우에는 테스트 실패가 아닐까요?
```suggestion
        // then
        assertThat(result).isInstanceOf(GameResultUiState.Status::class.java)
        val actual = (result as? GameResultUiState.Status)?.status
        assertThat(actual).isEqualTo(TictactoeStatus.Progress)
```

2023-09-01 20:50 UTC, namjackson commented on tictactoe-app/src/test/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModelTest.kt
> +        viewModel = TictactoeViewModel()
```
        val progressGame = TictactoeGame( ... 초기화 ... )
        viewModel = TictactoeViewModel(progressGame)
```

변경전 처럼, TictactoeGame의 defalut값을 생성시점에 입력받는 구조라면,
테스트 작성시 given절을 좀더 명확하게 작성할수 있을거 같아요!

2023-09-01 20:50 UTC, namjackson commented on tictactoe-app/src/test/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModelTest.kt
> +        viewModel = TictactoeViewModel()
현재의 테스트 코드의 경우 외에도,
O가 승리하는 케이스, 무승부가 나는 케이스, 이미 둔곳을 다시 두는 케이스 등 다양한 케이스들을 추가할수 있을거같아요!
여유가 되신다면, 상세한 케이스도 테스트를 작성해보면 좋을거같아요 😄 
(도메인 쪽도 동일해요!)

2023-09-01 20:51 UTC, merged

2023-09-02 13:28 UTC, minhyukseul commented on tictactoe-app/src/test/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModelTest.kt
> +        }
코드 보면서 한 수 배웠습니다.

2023-09-02 13:32 UTC, minhyukseul commented on tictactoe-app/src/test/java/camp/nextstep/edu/tictactoe/viewmodel/TictactoeViewModelTest.kt
> +        viewModel = TictactoeViewModel()
네 이게 제가 TDD하면서 사실 좀 고민되는 부분인데요. 테스트 케이스 자체가 중복적으로 도메인에도 있고 viewmodel에도 있고 하다 보니 이게 현업에서 이런 경우 굉장히 버든이 될 것 같다는 생각이 들더라고요. 그래도 저렇게 하는게 맞는거겠죠?