Step2 - 틱택토 랜덤
next-step/android-tictactoe pull request #24
Opened 2023-09-02 10:26 UTC by oyj7677

랜덤요소를 추가했습니다. 
Game클래스에 너무 많은 기능이 추가된 거 같아 Board와 Rule에 나누고 싶은데 기준을 잘 모르겠습니다.

요구사항의 테스트 시 무작위성을 제거한다는 어떤 걸 의미하나요?

2023-09-02 16:00 UTC, AnKyungMoo requested changes
이전 미션의 요구사항이 잘 반영되었네요 👍 👍 
미션 진행중에 반영되었으면 좋을 부분 코멘트 감겨두었어요~
고민 중이신 점도 추가 코멘트 남겨두겠습니다.
step2에서도 같이 잘 진행해보면 좋겠습니다 :)

2023-09-02 16:00 UTC, AnKyungMoo commented on tictectoe-domain/src/main/java/com/example/tictectoe_domain/Cell.kt
> +enum class Cell {
이름을 Cell로 바꿔준 것이 훨씬 의미적으로 좋은거같아요 👍 👍

2023-09-02 16:00 UTC, AnKyungMoo commented on tictectoe-domain/src/main/java/com/example/tictectoe_domain/Game.kt
> +import java.util.Random
java의 random말고, kotlin의 random함수를 사용해보세요! 😀

2023-09-02 16:00 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/tictactoe/ImgBindingAdapter.kt
> +}
```suggestion
@BindingAdapter("imgRes")
fun loadImage(imageView: ImageView, cell: Cell) {
    when (cell) {
        Cell.PLAYER1 -> {
            imageView.setImageResource(R.drawable.ic_x_black)
        }
        Cell.PLAYER2 -> {
            imageView.setImageResource(R.drawable.ic_o_black)
        }
        Cell.NONE -> {
            imageView.setImageResource(0)
        }
    }
}
```

Nit: 큰 의미가 없을 땐 object로 감싸주지 않고 최상위 함수로 두어도 괜찮습니다.

2023-09-02 16:00 UTC, AnKyungMoo commented on app/src/test/java/camp/nextstep/edu/tictactoe/TictactoeViewModelTest.kt
> +        assertThat(viewModel.board.value!![1]).isEqualTo(Cell.PLAYER1)
테스트코드긴하지만 `!!`는 최대한 지양하는 것이 좋습니다.
`!!`는 크래시를 유발하기 때문인데요. 위의 경우에는 notNull을 같이 체크해주는 것이 더욱 좋겠네요!

2023-09-02 16:00 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/tictactoe/TictactoeViewModel.kt
> +   private var game: Game
game 객체 자체가 변경되는 일이 없다면 val을 이용해주는 것이 좋습니다.

2023-09-02 16:00 UTC, AnKyungMoo commented on tictectoe-domain/src/main/java/com/example/tictectoe_domain/GameStatus.kt
> +}
누구의 턴인지 알고 있는 것과, 게임의 결과를 아는 것이 같은 enum에 묶여있으니 의미가 조금 섞인다는 느낌이 드네요..!
분리해보면 더 좋다고 느껴질 것 같아요 :)

2023-09-02 16:00 UTC, AnKyungMoo commented on tictectoe-domain/src/main/java/com/example/tictectoe_domain/TictectoeBoard.kt
> +            _tictectoeBoard[i] = Cell.NONE
forEach를 이용하면 더욱 간편하게 보드를 초기화할 수 있습니다.

2023-09-02 16:00 UTC, AnKyungMoo commented on tictectoe-domain/src/main/java/com/example/tictectoe_domain/TictectoeBoard.kt
> +    private val _tictectoeBoard = MutableList(10){ Cell.NONE}
코드 정렬 한 번 부탁드립니다!

2023-09-02 16:00 UTC, AnKyungMoo commented on tictectoe-domain/src/main/java/com/example/tictectoe_domain/TictectoeBoard.kt
> +        if(gameStatus == GameStatus.TURN_PLAYER1) {
GameStatus가  나뉘게 된다면, 해당 코드는 when으로 바꿔주는 것이 훨씬 좋겠네요!

2023-09-02 16:03 UTC, AnKyungMoo commented
> Game클래스에 너무 많은 기능이 추가된 거 같아 Board와 Rule에 나누고 싶은데 기준을 잘 모르겠습니다.

Game이 Turn과 관련된 책임을 많이 들고있네요! 이 부분 고민해서 수행해보시면 좋을 것 같습니다 😀
추가적으로 모르겠다면 다시 한 번 코멘트 남겨주세요!!

> 요구사항의 테스트 시 무작위성을 제거한다는 어떤 걸 의미하나요?

테스트 진행때 랜덤이 있다면 정답을 확인하기 어렵습니다.
현재 영재님께서는 랜덤하게 더해진 값을 알기위해서 보드 전체를 탐색하는 방법을 선택해주셨는데요.
값을 주입함으로써 순회하지 않고, 프로덕트 코드에서는 랜덤하게, 테스트 코드에서는 특정 위치를 확인할 수 있습니다.
고민해서 수행해보고 이해가 어렵다면 추가 질문주세요!

2023-09-03 15:46 UTC, AnKyungMoo requested changes
Game이 현재 너무 많은 책임을 들고있네요..!
관련해서 수정한 뒤의, 요구사항의 랜덤요소 배제 관련하여 고민해볼 수 있으면 좋겠습니다 :)
DM으로 연락주신 부분에 답변 드렸으니, 확인 후에 어려운점이 있다면 추가적으로 DM 주시거나 코멘트 주시면 답변 드리도록 하겠습니다 :)
조금 더 화이팅해보아요!! 👍
수정 후 다시 요청주시면 감사합니다. :)

2023-09-03 15:46 UTC, AnKyungMoo commented on tictectoe-domain/src/main/java/com/example/tictectoe_domain/Game.kt
> +    fun selectBoard(position: Int, nextPosition: Int? = null) {
selectBoard()와 autoSelectBoard()는 게임 모드에 책임을 옮겨보는 것을 더 추천드립니다!
게임 자체가 어떤 방식으로 진행되는지를 직접 알지 않는 것이 더욱 좋습니다.

2023-09-03 15:46 UTC, AnKyungMoo commented on tictectoe-domain/src/main/java/com/example/tictectoe_domain/TictectoeBoard.kt
> +        }
PlayerTurn은 두가지 밖에 없는 enum class이므로 when으로 변경해주는 것이 더욱 바람직합니다.

2023-09-03 15:46 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/tictactoe/TictactoeViewModel.kt
> +        game.changeRandomMode()
Nit: 파라미터를 이용하여 하나의 함수로 합치는 것은 어떠신가요?

2023-09-03 15:46 UTC, AnKyungMoo commented on tictectoe-domain/src/main/java/com/example/tictectoe_domain/Game.kt
> +    }
이 부분도 파라미터를 통해 하나의 함수로 합쳐보는 것은 어떨까요?

2023-09-04 15:19 UTC, oyj7677 commented
랜덤 요소 배제하는 말은 아직 이해가 가지 않습니다.
저의 생각은 다음과 같습니다.
 - 랜덤에 대한 테스트를 하지 않는 것인가?
 - 랜덤 모드일 경우 자동으로 랜덤하게 선택되는데 이 부분을 어떤 방식으로 테스트에서 지정할 수 있는가?
 - 프로덕트 코드가 테스트 코드에 대해 고려되어야 하는가?

2023-09-04 15:25 UTC, oyj7677 commented
아직 부족한 점 많지만 경무님의 좋은 리뷰 덕분에 이후 안드로이드 개발에 천천히 알아가고 있는 것 같습니다.
강의와 과제가 후반부로 갈수록 저에게 난이도가 있고 성실하지 못하여 정해진 기간 내에 과제를 모두 진행하지 못하였습니다.
비록 강의 기간이 끝났지만 이후 과제 진행에 대해 좋은 리뷰 부탁드리겠습니다. 감사합니다.

2023-09-04 16:48 UTC, AnKyungMoo approved these changes
이번 step도 고생 많으셨습니다!
질문 주신 내용은 코멘트 남겨놓도록 하겠습니다 😀
다음 step 진행을 위해 머지하도록 하겠습니다~

2023-09-04 16:57 UTC, AnKyungMoo commented
> 랜덤에 대한 테스트를 하지 않는 것인가?
> 랜덤 모드일 경우 자동으로 랜덤하게 선택되는데 이 부분을 어떤 방식으로 테스트에서 지정할 수 있는가?

랜덤에 대한 테스트를 진행할 수 있으면 좋지만, **틱택톡 미션**에서는 수행하지 않습니다. 진행할 수 있다면 좋지만 주된 내용은 아니기 때문입니다.

> 프로덕트 코드가 테스트 코드에 대해 고려되어야 하는가?

테스트코드 작성을 위해서라면 어느정도 고려하는 것이 좋다고 생각합니다.
테스트코드의 장점들을 잘 이용하기 위해서라면 프로덕트 코드의 로직에 영향이 가지 않는 선에서 최대한 작성해나가는 것이 바람직하다고 생각해요.
테스트코드에 대한 트레이드 오프는 개개인에 따라 판단하는게 달라지기 때문에 어느정도의 선을 말씀드리기는 어렵지만, 어느정도는 감내하고 작성하시는 분들도 계시기때문에 과정 진행하시면서 같이 고민해보시면 좋을 것 같습니다 :)

2023-09-04 16:57 UTC, merged