Step1
next-step/android-tictactoe pull request #3
Opened 2023-02-27 14:17 UTC by jpoh281

리뷰어님 안녕하세요?
틱택토가 생각보다 어려워서 PR 좀 많이 늦었네요...

이번 미션 잘부탁드립니다!!

2023-02-28 15:29 UTC, AnKyungMoo requested changes
종표님 안녕하세요~ 
틱택토 과제 리뷰를 담당하게된 안경무라고합니다.
전체적으로 객체의 책임 분리가 잘 되어있고 테스트 함수도 잘 작성되어있네요!! 👍 👍 
하지만 승리조건과 관련하여 이슈가 있어서 코멘트 남겼습니다!
수정사항 반영하고나서 다시 리뷰요청주시면 감사하겠습니다 :)

2023-02-28 15:29 UTC, AnKyungMoo commented on domain/src/main/java/com/example/domain/Board.kt
> +        require(blocks.size == 9) {
매직넘버는 웬만하면 사용하지 않는 것이 좋습니다.
처음 보는 사람은 9의 의미를 알기 위해 다른 코드를 봐서 이해해야하는 이슈가 발생할 수 있어요!
또한 createEmptyBoard에서도 같은 숫자를 이용하고있는데요~
하나의 상수로 관리된다면 한 번에 수정이 가능해서 조금 더 유연하고 실수를 줄이는 개발을 할 수 있게 됩니다!

2023-02-28 15:29 UTC, AnKyungMoo commented on domain/src/main/java/com/example/domain/Game.kt
> +    }
8개까지에서 승부가 나지 않다가 9개째에서 한 줄을 완성하는 경우에도 무승부 처리가 되네요! 🥲
해당 로직을 수정해보는 것이 좋을 것 같습니다

2023-02-28 15:29 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/tictactoe/TicTacToeViewModel.kt
> +}
별도의 파일에서 관리하는 것을 추천드려요~
해당 Assign 함수는 뷰모델과 직접적인 관련이 없어보이네요~

2023-02-28 15:29 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/tictactoe/TicTacToeViewModel.kt
> +    private var game: Game
```suggestion
    private val game: Game
```
별도로 game 객체를 새로 선언하는 부분이 없는 경우 val로 만들어주는 것이 좋습니다!
init scope에서 초기화를 진행해준다면 val로 하더라도 문제가 되지 않습니다 :)

2023-02-28 15:29 UTC, AnKyungMoo commented on domain/src/main/java/com/example/domain/Block.kt
> +        return "EmptyBlock()"
Nit: toString에도 괄호가 들어가는 이유가 있을까요?
그냥 궁금해서 물어봅니다..! 😅

2023-02-28 15:29 UTC, AnKyungMoo commented on domain/src/main/java/com/example/domain/Block.kt
> +sealed class Block
sealed class를 이용하여 블록의 상태를 나타낼 수 있도록 하였네요! 👍 👍 
깔끔하고 의미전달이 잘 되어서 좋아요~

2023-02-28 15:29 UTC, AnKyungMoo commented on domain/src/main/java/com/example/domain/Board.kt
> +    private val blocks = blocks.toMutableList()
Nit: blocks를 행렬의 형태로 나타내는 것도 고민해보시면 좋을 것 같습니다.
1차원 리스트와 2차원 리스트는 결국 사용하는 메모리도 거의 같고, 동작에도 크게 차이는 없을 수 있지만 행렬의 형태가된다면 조금 더 직관적으로 파악할 수 있을 것 같아요.
또한 1차원 리스트의 형식일 때는 3개마다 행이 바뀐다는 사실을 직접적으로 인식하고있어야하는 이슈가 발생합니다.
혹은 16개로 판의 크기가 변경된다면 3번이 1번째 줄로 올라오게 되어서 의미도 달라지게되구요..! (물론 해당 과제에서는 판의 크기가 변경되는 요구사항이 없습니다.)

해당 코멘트는 꼭 반영하지 않으셔도 되지만 한 번 고민해보시면 좋을 것 같아서 코멘트 남겼습니다!

2023-02-28 15:29 UTC, AnKyungMoo commented on domain/src/main/java/com/example/domain/Game.kt
> +class Game(turn: Int = 0, board: Board = Board.createEmptyBoard()) {
매직넘버의 사용을 줄이고 상수화 해보는 것은 어떨까요?
0이 가지는 의미를 상수로 표현한다면 더욱 좋을 것 같아요!

2023-02-28 15:29 UTC, AnKyungMoo commented on domain/src/main/java/com/example/domain/Turn.kt
> +        require(value in 0..8) {
턴이 9개를 넘어가지 않도록 하는 것도 판의 크기와 관련이 있네요..!
```suggestion
        require(value in 0 until BOARD_SIZE) {
```
와 같이 판의 크기를 상수화하고 until을 이용하는 것이 조금 더 직관적으로 보여줄 수 있다고 느껴집니다~

2023-02-28 15:29 UTC, AnKyungMoo commented on domain/build.gradle.kts
> +    id("java-library")
자바 라이브러리는 필요해보이지 않네요!
순수 코틀린 모듈로써 동작하도록 변경해보는 것은 어떨까요?

2023-02-28 15:29 UTC, AnKyungMoo commented on domain/src/test/kotlin/com/example/domain/BoardTest.kt
> +        fun `Empty Block이 없으면 isDraw는 true를 반환한다`() {
위에서 남긴 코멘트 처럼 마지막 블록을 기준으로 승리조건이 나올 수 있습니다.
승리조건에 대해 수정하면서 테스트함수도 같이 수정이 되어야하겠네요~

2023-02-28 15:32 UTC, AnKyungMoo commented
추가로 요구사항에 대한 내용을 README를 통해 작성해주시면 좋습니다..!

2023-03-01 13:32 UTC, jpoh281 commented
안녕하세요?
꼼꼼한 리뷰 감사합니다.

매직넘버에 대해서 말씀해주셔서 감사합니다. 이게 자주 피드백받는 내용인데 종종 잊어버리네요. 😅

toString에 괄호가 들어간 이유는... Android Studio 자동 생성 사용하니까 그렇게 만들어줬어요..

오늘 태현님 틱택토 피드백을 보니까 맵으로 하는것도 좋고, 리뷰어님이 말씀해주신것처럼 2차원 배열을 해도 좋겠다는 생각이 들었어요.
2차원 배열로 바꾸면 외부에서는 영향을 받지않도록 [position ~/ 3][position % 3]으로 하도록 하면 되겠다는 생각이 들어요.
이번에는 변화에 완전히 닫혀있는 상태라 변경하는 대신 좀 더 이해하기 쉽도록 WIDTH, HEIGHT 라는 상수를 만들었습니다.

다음 미션부터는 README를 통해 작성하겠습니다 👍

2023-03-02 08:59 UTC, AnKyungMoo approved these changes
코드가 전체적으로 너무 깔끔하고 커밋 단위가 잘 나뉘어져 있어서 리뷰할 때 너무 좋았습니다 👍 👍 
추가적으로 반영해볼만한 부분 간단하게 코멘트 추가했습니다~
다음 과제 진행을 위해 머지하도록 할게요~

2023-03-02 08:59 UTC, AnKyungMoo commented on app/src/main/res/layout/activity_main.xml
> +        <import type="camp.nextstep.edu.tictactoe.AssignBinderKt" />
해당 라인은 없어도 bindingAdapter를 이용한 함수는 동작합니다!

2023-03-02 08:59 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/tictactoe/AssignBinder.kt
> +fun setAssign(view: View?, block: Block?) {
정확하게는 Assign의 기능을 하는 것이 아닌, assign 된 곳의 이미지가 변경되는 곳이라 이미지 변경의 의미가 나타나도록 함수명을 수정해보는 것은 어떨까요?

2023-03-02 08:59 UTC, AnKyungMoo commented on app/src/main/java/camp/nextstep/edu/tictactoe/AssignBinder.kt
> +@BindingAdapter("android:assign")
Nit: 관례적으로 BindingAdapter의 파일명으로 ~~Binder보단 ~~BindingAdapter라고 많이 사용하게 되더라구요
참고만 해주시면 좋을 것 같습니다!

2023-03-02 08:59 UTC, merged